# Generated by Django 4.1.2 on 2022-10-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='img/city/')),
                ('body', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='img/hotel/')),
                ('body', models.TextField(max_length=200)),
                ('cityName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tur.city')),
            ],
        ),
    ]
