# Generated by Django 4.1.3 on 2022-11-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0002_alter_city_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='body',
            field=models.TextField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='city',
            name='photo',
            field=models.ImageField(upload_to='img/city/', verbose_name='Фото'),
        ),
    ]
