# Generated by Django 4.1.2 on 2022-11-01 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0003_alter_hotel_cityname_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='cityName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='tur.city'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotelName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='tur.hotel'),
        ),
    ]
