# Generated by Django 4.1.2 on 2022-12-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tur', '0003_alter_city_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='author',
        ),
    ]
