# Generated by Django 4.1.3 on 2022-11-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='post',
            field=models.CharField(choices=[('П', 'Пользователь'), ('М', 'Менеджер'), ('А', 'Админ')], default='Пользователь', max_length=50, verbose_name='Должность сотрудника'),
        ),
    ]
